### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by KiranGadhavi** [SchoolOfCode/bc17-w7d1-workshop-responsive-landing-page-brilliant-json-krew#1]
```[tasklist]
### Tasks
- [x] Make HTML plan
- [x] Label design image with components
- [x] Make grid/flex plan
- [x] Create boilerplate starter files
- [x] Create grid container
```
